---
- name: Copy Alertmanager service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - daemon_reload
    - restart_alertmanager_service
  when:
    ansible_distribution_major_version == "18" or ansible_distribution_major_version == "16"

- name: Copy init script of Alertmanager
  copy:
    src: alertmanager.init
    dest: /etc/init.d/alertmanager
    mode: '0700'
  when:
    ansible_distribution_major_version == "14"
  notify:
    - restart_alertmanager_service
