- name: Creating alertmanager service user
  user:
    name: alertmanager
    shell: /sbin/nologin
    state: present

- name: Downloading the binary file for Alertmanager
  unarchive:
    src: "{{ alertmanager_base_url }}/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /opt/
    remote_src: yes

- name: Move the binary executable file
  copy:
    src: /opt/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager
    dest: /usr/bin/
    mode: '0700'
    remote_src: yes

- name: Create Data, Configuration and log directory for Alertmanager
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  with_items:
    - /var/lib/alertmanager
    - /etc/alertmanager
    - /var/log/alertmanager

- name: Copying Alertmanager Configuration file
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml

- name: Adding Email Template for Alertmanager
  copy:
    src: email.tmpl
    dest: /etc/alertmanager/email.tmpl
