---
- name: Checking Pprometheus hosts are defined or not
  fail:
    msg: "Playbook failed due to missing or empty required group 'prometheus'"
  when: groups['prometheus'] is not defined or groups['prometheus']|length == 0
