---
- name: Creating service user
  user:
   name: alertmanager
   shell: /bin/false
   state: present

- name: Download and install Unzip
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - libselinux-python

- name: Installing Systemd on Centos
  yum:
    name: systemd
    state: present
  when:
    ansible_distribution_major_version == "7"

- name: Checking Alertmanager Binary
  stat:
    path: "{{ prometheus_binary_path }}/alertmanager"
  register: check_alartmanager_binary

- name: Downloading the binary file for Alertmanager
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
  when: check_alartmanager_binary.stat.exists == false

- name: Move the binary executable file
  copy:
    src: /opt/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager
    dest: /usr/bin/
    mode: 0550
    remote_src: yes

- name: Copy init script of Alertmanager for Centos 6
  copy:
    src: alertmanager.init
    dest: /etc/init.d/alertmanager
    mode: 0550
  when:
    ansible_distribution_major_version == "6"

- name: Create directory for Alertmanager Configuration, Data and Logs
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  with_items:
    - /etc/alertmanager
    - /var/lib/alertmanager
    - /var/log/alertmanager

- name: Adding Alertmanager Configuration
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml

- name: Adding Email Template for Alertmanager
  copy:
    src: email.tmpl
    dest: /etc/alertmanager/email.tmpl

- name: Copy Service for Prometheus
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - reload_alertmanager_service
    - restart_alertmanager_service
  when:
    ansible_distribution_major_version == "7"

- name: Restarting the init alertmanager service
  service:
    name: alertmanager
    state: started
  when:
    ansible_distribution_major_version == "6"

- name: Copy Prometheus Configuratio file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  notify:
    - restart_alertmanager_service
  delegate_to: "{{ item }}"
  loop: "{{ groups['prometheus'] }}"
...
