---
- name: Download the dependencies
  yum:
    name: libselinux-python
    state: present
 
- name: Copying Alertmanger service file for Centos 7
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - daemon_reload
    - restart_alertmanager_service
  when:
    ansible_distribution_major_version == "7"

    
- name: Copy init script of Alertmanager for Centos 6
  copy:
    src: alertmanager.init
    dest: /etc/init.d/alertmanager
    mode: '0700'
  notify:
    - restart_alertmanager_service
  when:
    ansible_distribution_major_version == "6"

