---
# handlers file for alertmanager
- name: daemon_reload
  systemd:
    daemon_reload: yes

- name: restart_alertmanager_service
  service:
    name: alertmanager
    state: restarted
    enabled: yes
