---
# handlers file for alertmanager
- name: daemon_reload
  systemd:
    daemon_reload: "yes"

- name: restart_alertmanager_service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: "yes"
  loop:
    - alertmanager
    - prometheus

- name: reload_calert_service
  service:
    name: calert
    state: restarted
    enabled: "yes"
...
