---
# handlers file for alertmanager
- name: reload_alertmanager_service
  systemd:
    daemon_reload: yes

- name: restart_alertmanager_service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - alertmanager
    - prometheus
...
