---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Alertmanager
  ansible.builtin.systemd:
    name: "{{ alertmanager_service_name }}"
    state: restarted
